name: qr_scanner_app
description: A simple QR code scanner app.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
